packages:
  - apps/*
ignoredBuiltDependencies:
  - lmdb
onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - lmdpnb
  - msgpackr-extract
  - prisma
publicHoistPattern:
  - esbuild
  - typescript
  - typegraphql-prisma
